// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherStation.Web.Api.Data;

namespace WeatherStation.Web.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191201155547_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherStation.Web.Api.Models.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AirPressure");

                    b.Property<float>("Humidity");

                    b.Property<float>("Temperature");

                    b.Property<DateTime>("Time");

                    b.Property<string>("WeatherStationName");

                    b.HasKey("MeasurementId");

                    b.HasIndex("WeatherStationName");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("WeatherStation.Web.Api.Models.WeatherStation", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Name");

                    b.ToTable("WeatherStations");
                });

            modelBuilder.Entity("WeatherStation.Web.Api.Models.Measurement", b =>
                {
                    b.HasOne("WeatherStation.Web.Api.Models.WeatherStation", "WeatherStation")
                        .WithMany("Measurements")
                        .HasForeignKey("WeatherStationName");
                });
#pragma warning restore 612, 618
        }
    }
}
